name: run-script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Executar o script
        env:
          CARTPANDA_API_TOKEN: ${{ secrets.CARTPANDA_API_TOKEN }}
        run: python dropi_to_cartpanda.py
