name: Run Dropi to Cartpanda Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar o script Dropi → Cartpanda
        run: python dropi_to_cartpanda.py
        env:
          DROPPI_EMAIL: ${{ secrets.DROPPI_EMAIL }}
          CARTPANDA_API_TOKEN: ${{ secrets.CARTPANDA_API_TOKEN }}
